# ==============================
#  CONFIGURACIÃ“N DE GITHUB PAGES
#  Proyecto: SENA Respira IoT
# ==============================

theme: jekyll-theme-cayman

title: "ðŸŒ¿ Proyecto Respira IoT"
description: "Monitoreo ambiental con sensores MQ-135 y higrÃ³metro conectados a ESP32 | ImplementaciÃ³n SENA Pasto"

# Opciones adicionales
show_downloads: false
google_analytics: false

# PersonalizaciÃ³n del encabezado
author: "Aprendices SENA - Lope"
github:
  is_project_page: true
  repository_url: "https://github.com/marlilycelis/sena-proyecto-respira"
